import type { Metadata } from "next";
import "../../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({


  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" className="overflow-x-hidden scroll-smooth" >
      
    //   <body className='relative bg-[#FDFDFD]' >
    <>
            {children}
     
      </>
    //   {/* </body>
    // </html> */}
  );
}
