import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderNav from "./(frontend)/_component/header";
import { AOSInit } from "./(frontend)/_component/aos";
import { Locomotive } from "./(frontend)/_component/locomotive";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({


  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden scroll-smooth" >
      
      <AOSInit />
      <body className='relative bg-[#FDFDFD]' >
      <HeaderNav/>
        {children}
      </body>
      {/* <Locomotive/> */}
    </html>
  );
}
