import type { Metadata } from "next";
import "../globals.css";
import HeaderNav from "./_component/header";
import { AOSInit } from "./_component/aos";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<HeaderNav />
			{children}
		</>
	);
}
